INTERVENTIONS = [
    {
        "id": "shade_structure",
        "name": "Shade Structure",
        "category": "passive_cooling",
        "description": "Immediate solar-load reduction for exposed pedestrian or waiting areas.",
        "effect_profile": {
            "hazard_reduction": 0.12,
            "exposure_reduction": 0.08,
            "vulnerable_benefit_multiplier": 1.10,
            "duration_factor": 1.00,
        },
        "cost_model": {"base_cost": 18000, "unit": "site"},
        "constraints": {"min_road_fraction": 0.15, "max_shade_fraction": 0.55},
        "evidence_level": "high",
        "base_confidence": 0.86,
        "implementation_months": 2,
    },
    {
        "id": "tree_canopy",
        "name": "Tree Canopy Expansion",
        "category": "nature_based",
        "description": "Canopy intervention targeting solar exposure and long-term local cooling.",
        "effect_profile": {
            "hazard_reduction": 0.10,
            "exposure_reduction": 0.05,
            "vulnerable_benefit_multiplier": 1.08,
            "duration_factor": 0.90,
        },
        "cost_model": {"base_cost": 12000, "unit": "cell"},
        "constraints": {"max_vegetation_fraction": 0.65, "min_solar_exposure_index": 0.40},
        "evidence_level": "medium_high",
        "base_confidence": 0.78,
        "implementation_months": 12,
    },
    {
        "id": "cool_roof",
        "name": "Cool Roof Program",
        "category": "materials",
        "description": "High-albedo roof treatment for built-form heat reduction.",
        "effect_profile": {
            "hazard_reduction": 0.07,
            "exposure_reduction": 0.03,
            "vulnerable_benefit_multiplier": 1.02,
            "duration_factor": 1.00,
        },
        "cost_model": {"base_cost": 24000, "unit": "cell"},
        "constraints": {"min_building_fraction": 0.20},
        "evidence_level": "high",
        "base_confidence": 0.84,
        "implementation_months": 4,
    },
    {
        "id": "cool_pavement",
        "name": "Cool Pavement",
        "category": "materials",
        "description": "Reflective pavement treatment for road/hardscape-dominated cells.",
        "effect_profile": {
            "hazard_reduction": 0.06,
            "exposure_reduction": 0.03,
            "vulnerable_benefit_multiplier": 1.00,
            "duration_factor": 1.00,
        },
        "cost_model": {"base_cost": 30000, "unit": "cell"},
        "constraints": {"min_road_fraction": 0.25, "min_impervious_fraction": 0.45},
        "evidence_level": "medium",
        "base_confidence": 0.72,
        "implementation_months": 3,
    },
    {
        "id": "cooling_center",
        "name": "Cooling Center Activation",
        "category": "operational",
        "description": "Immediate exposure reduction through accessible cooled refuge.",
        "effect_profile": {
            "hazard_reduction": 0.00,
            "exposure_reduction": 0.18,
            "vulnerable_benefit_multiplier": 1.30,
            "duration_factor": 1.00,
        },
        "cost_model": {"base_cost": 9000, "unit": "activation"},
        "constraints": {"min_vulnerability_index": 0.45},
        "evidence_level": "high",
        "base_confidence": 0.88,
        "implementation_months": 0.25,
    },
]
