from datetime import datetime,timezone
from uuid import uuid4
from geoalchemy2 import Geometry
from sqlalchemy import JSON,DateTime,Float,ForeignKey,Integer,String,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from app.db.base import Base
def utcnow(): return datetime.now(timezone.utc)
class Area(Base):
    __tablename__='areas'; id:Mapped[str]=mapped_column(String(64),primary_key=True); city_id:Mapped[str]=mapped_column(String(64),ForeignKey('cities.id',ondelete='CASCADE'),nullable=False); name:Mapped[str]=mapped_column(String(160),nullable=False); area_type:Mapped[str]=mapped_column(String(64),default='aoi'); geometry=mapped_column(Geometry('MULTIPOLYGON',srid=4326),nullable=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class ThermalCell(Base):
    __tablename__='thermal_cells'; __table_args__=(UniqueConstraint('area_id','grid_key',name='uq_thermal_cell_grid'),); id:Mapped[str]=mapped_column(String(64),primary_key=True); area_id:Mapped[str]=mapped_column(String(64),ForeignKey('areas.id',ondelete='CASCADE'),nullable=False); grid_key:Mapped[str]=mapped_column(String(128),nullable=False); resolution_m:Mapped[int]=mapped_column(Integer,nullable=False); geometry=mapped_column(Geometry('POLYGON',srid=4326),nullable=False); centroid=mapped_column(Geometry('POINT',srid=4326),nullable=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class ThermalObservation(Base):
    __tablename__='thermal_observations'; __table_args__=(UniqueConstraint('cell_id','observed_at','source_name',name='uq_thermal_observation'),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid4())); cell_id:Mapped[str]=mapped_column(String(64),ForeignKey('thermal_cells.id',ondelete='CASCADE'),nullable=False); observed_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False); temperature_c:Mapped[float]=mapped_column(Float,nullable=False); apparent_temperature_c:Mapped[float|None]=mapped_column(Float); humidity_pct:Mapped[float|None]=mapped_column(Float); heat_index_c:Mapped[float|None]=mapped_column(Float); source_type:Mapped[str]=mapped_column(String(32),nullable=False); source_name:Mapped[str]=mapped_column(String(128),nullable=False); source_activity_id:Mapped[str|None]=mapped_column(String(128)); quality_label:Mapped[str]=mapped_column(String(32),default='observed'); metadata_json:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class ThermalBaseline(Base):
    __tablename__='thermal_baselines'; __table_args__=(UniqueConstraint('cell_id','bucket_key',name='uq_thermal_baseline'),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid4())); cell_id:Mapped[str]=mapped_column(String(64),ForeignKey('thermal_cells.id',ondelete='CASCADE'),nullable=False); bucket_key:Mapped[str]=mapped_column(String(64),nullable=False); mean_c:Mapped[float]=mapped_column(Float,nullable=False); std_c:Mapped[float]=mapped_column(Float,nullable=False); p90_c:Mapped[float]=mapped_column(Float,nullable=False); sample_count:Mapped[int]=mapped_column(Integer,nullable=False); computed_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class ThermalMetric(Base):
    __tablename__='thermal_metrics'; __table_args__=(UniqueConstraint('cell_id','observed_at',name='uq_thermal_metric'),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid4())); cell_id:Mapped[str]=mapped_column(String(64),ForeignKey('thermal_cells.id',ondelete='CASCADE'),nullable=False); observed_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False); anomaly_c:Mapped[float|None]=mapped_column(Float); z_score:Mapped[float|None]=mapped_column(Float); exceedance_c:Mapped[float|None]=mapped_column(Float); persistence_hours:Mapped[float]=mapped_column(Float,default=0); severity_score:Mapped[float]=mapped_column(Float,nullable=False); confidence:Mapped[float]=mapped_column(Float,nullable=False); components_json:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class ThermalHotspot(Base):
    __tablename__='thermal_hotspots'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid4())); area_id:Mapped[str]=mapped_column(String(64),ForeignKey('areas.id',ondelete='CASCADE'),nullable=False); detected_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False); status:Mapped[str]=mapped_column(String(32),default='active'); severity:Mapped[str]=mapped_column(String(32),nullable=False); peak_temperature_c:Mapped[float]=mapped_column(Float,nullable=False); mean_anomaly_c:Mapped[float]=mapped_column(Float,nullable=False); max_persistence_hours:Mapped[float]=mapped_column(Float,nullable=False); cell_count:Mapped[int]=mapped_column(Integer,nullable=False); geometry=mapped_column(Geometry('MULTIPOLYGON',srid=4326),nullable=False); confidence:Mapped[float]=mapped_column(Float,nullable=False); metadata_json:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class ThermalEvent(Base):
    __tablename__='thermal_events'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid4())); area_id:Mapped[str]=mapped_column(String(64),ForeignKey('areas.id',ondelete='CASCADE'),nullable=False); event_type:Mapped[str]=mapped_column(String(64),nullable=False); status:Mapped[str]=mapped_column(String(32),default='active'); started_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False); ended_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); peak_severity_score:Mapped[float]=mapped_column(Float,nullable=False); peak_temperature_c:Mapped[float]=mapped_column(Float,nullable=False); max_persistence_hours:Mapped[float]=mapped_column(Float,nullable=False); hotspot_count:Mapped[int]=mapped_column(Integer,nullable=False); confidence:Mapped[float]=mapped_column(Float,nullable=False); summary_json:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
