CONTEXT_FIXTURE = {
    "phx-cell-01": {
        "population": 420,
        "population_density_km2": 6100,
        "vulnerable_population": 92,
        "vulnerability_index": 0.42,
        "vegetation_fraction": 0.18,
        "impervious_fraction": 0.61,
        "building_fraction": 0.29,
        "water_fraction": 0.00,
        "shade_fraction": 0.22,
        "road_fraction": 0.34,
        "solar_exposure_index": 0.73,
        "nighttime_retention_index": 0.57,
        "data_quality": 0.82,
    },
    "phx-cell-02": {
        "population": 780,
        "population_density_km2": 11300,
        "vulnerable_population": 235,
        "vulnerability_index": 0.71,
        "vegetation_fraction": 0.08,
        "impervious_fraction": 0.78,
        "building_fraction": 0.41,
        "water_fraction": 0.00,
        "shade_fraction": 0.12,
        "road_fraction": 0.39,
        "solar_exposure_index": 0.89,
        "nighttime_retention_index": 0.79,
        "data_quality": 0.86,
    },
    "phx-cell-03": {
        "population": 990,
        "population_density_km2": 14300,
        "vulnerable_population": 318,
        "vulnerability_index": 0.76,
        "vegetation_fraction": 0.05,
        "impervious_fraction": 0.82,
        "building_fraction": 0.34,
        "water_fraction": 0.00,
        "shade_fraction": 0.09,
        "road_fraction": 0.46,
        "solar_exposure_index": 0.93,
        "nighttime_retention_index": 0.84,
        "data_quality": 0.88,
    },
    "phx-cell-04": {
        "population": 360,
        "population_density_km2": 5200,
        "vulnerable_population": 76,
        "vulnerability_index": 0.36,
        "vegetation_fraction": 0.31,
        "impervious_fraction": 0.48,
        "building_fraction": 0.22,
        "water_fraction": 0.00,
        "shade_fraction": 0.39,
        "road_fraction": 0.27,
        "solar_exposure_index": 0.55,
        "nighttime_retention_index": 0.43,
        "data_quality": 0.80,
    },
}

FACILITY_FIXTURE = [
    {
        "id": "phx-school-01",
        "area_id": "phx-downtown",
        "name": "HELIOS Fixture School",
        "facility_type": "school",
        "vulnerability_weight": 2.0,
        "capacity": 850,
        "longitude": -112.0710,
        "latitude": 33.4480,
    },
    {
        "id": "phx-transit-01",
        "area_id": "phx-downtown",
        "name": "HELIOS Fixture Transit Stop",
        "facility_type": "transit",
        "vulnerability_weight": 1.2,
        "capacity": 300,
        "longitude": -112.0680,
        "latitude": 33.4520,
    },
    {
        "id": "phx-clinic-01",
        "area_id": "phx-downtown",
        "name": "HELIOS Fixture Clinic",
        "facility_type": "healthcare",
        "vulnerability_weight": 2.5,
        "capacity": 120,
        "longitude": -112.0730,
        "latitude": 33.4520,
    },
]
