"use client";
import Link from "next/link";import {Bar,BarChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {E,arr,n,providerOptimizer,money,fmt,s} from "@/lib/domain";import {useLive} from "./useLive";
export default function Command(){
 const p=useLive(E.provider),o=useLive(E.optimizer),sys=useLive(E.system);const a=arr(p.data),opt=providerOptimizer(o.data),st:any=sys.data??{};
 const teu=a.reduce((z,x)=>z+(n(x,"teu")??0),0),va=a.reduce((z,x)=>z+(n(x,"va_teu","vulnerable_teu")??0),0);
 const chart=a.map(x=>({cell:s(x,"cell_id"),TEU:n(x,"teu")??0,"VA-TEU":n(x,"va_teu","vulnerable_teu")??0})).sort((x,y)=>y["VA-TEU"]-x["VA-TEU"]);
 return <div className="page"><section className="command-hero"><div><div className="eyebrow">PHOENIX URBAN HEAT INTERVENTION OPERATING SYSTEM</div><h1>Don’t map the heat.<br/><em>Rewrite it.</em></h1><p>HELIOS turns provider-backed observations into exposure intelligence, cooling actions, optimized investment, climate-safe mobility and governed local AI.</p><div className="cta"><Link href="/atlas">Open Phoenix Thermal Atlas</Link><Link className="secondary" href="/investment">Investment Intelligence</Link></div></div><div className="decision-orb"><span>CLOSED LOOP</span><b>OBSERVE</b><i>→</i><b>DIAGNOSE</b><i>→</i><b>ACT</b></div></section>
 <div className="coverage-ribbon"><b>PHOENIX PLATFORM</b><span>Citywide OSM operating context</span><i>Current live provider footprint: downtown validation AOI · {a.length||4} verified cells</i></div>
 <section className="metrics five"><article className="metric"><span>Verified cells</span><b>{a.length||"—"}</b><small>live provider footprint</small></article><article className="metric"><span>Total TEU</span><b>{a.length?fmt(teu,1):"—"}</b><small>current live AOI</small></article><article className="metric"><span>VA-TEU</span><b>{a.length?fmt(va,1):"—"}</b><small>current live AOI</small></article><article className="metric accent"><span>Provider-native portfolio</span><b>{money(n(opt,"total_cost","cost"))}</b><small>budget {money(n(opt,"budget","budget_limit"))}</small></article><article className="metric"><span>Gemma 4</span><b>{st?.intelligence?.reachable?"LIVE":"CHECK"}</b><small>native FAST · firewall</small></article></section>
 <div className="command-grid"><section className="panel"><div className="eyebrow">CURRENT LIVE AOI</div><h2>Where burden concentrates</h2><div className="chart-wrap"><ResponsiveContainer width="100%" height={300}><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="cell"/><YAxis/><Tooltip/><Bar dataKey="TEU" fill="var(--cyan)"/><Bar dataKey="VA-TEU" fill="var(--acid)"/></BarChart></ResponsiveContainer></div></section><section className="panel"><div className="eyebrow">DECISION POSTURE</div><h2>Planning & preparedness</h2><div className="decision-card"><span>TRUTH BOUNDARY</span><b>Do not infer unobserved Phoenix.</b><p>HELIOS is citywide in architecture. Today’s live provider-validated footprint is downtown Phoenix; the platform explicitly marks unobserved areas rather than fabricating heat intelligence.</p></div><div className="mini-grid"><Link href="/atlas"><b>See coverage</b><span>Phoenix overview → live AOI</span></Link><Link href="/thermalway"><b>Protect movement</b><span>Thermal-safe routing</span></Link><Link href="/evidence"><b>Inspect evidence</b><span>Provenance & uncertainty</span></Link></div></section></div></div>
}
