"use client";
import Link from "next/link";
import {Bar,BarChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {E,arr,n,providerOptimizer,money,fmt,s} from "@/lib/domain";
import {useLive} from "./useLive";
import {startJudgeTour} from "./JudgeTour";

const FLOW=["THERMAL OBSERVATIONS","EXPOSURE","INTERVENTIONS","OPTIMIZATION","ACTION"];
export default function Command(){
 const provider=useLive(E.provider),optimizer=useLive(E.optimizer),system=useLive(E.system);
 const cells=arr(provider.data),opt=providerOptimizer(optimizer.data),runtime:any=system.data??{};
 const teu=cells.reduce((z,x)=>z+(n(x,"teu")??0),0),va=cells.reduce((z,x)=>z+(n(x,"va_teu")??0),0);
 const chart=cells.map(x=>({cell:s(x,"cell_id").replace("phx-cell-","Cell "),TEU:n(x,"teu")??0,"VA-TEU":n(x,"va_teu")??0}));
 const unavailable=provider.error||optimizer.error;
 return <div className="page command-page">
  <section className="judge-hero"><div className="hero-copy"><div className="eyebrow">PHOENIX URBAN HEAT INTERVENTION OPERATING SYSTEM</div><h1>Cities already know where it’s hot.<br/><em>HELIOS decides what to do next.</em></h1><p>FortyGuard observes urban heat. HELIOS converts those observations into exposure intelligence, cooling interventions, safer mobility, optimized investment and governed AI.</p><div className="brand-line">Don’t map the heat. <b>Rewrite it.</b></div><div className="cta"><button onClick={startJudgeTour}>Start 90-sec Judge Tour</button><Link className="secondary" href="/atlas">Explore live evidence</Link></div></div><div className="fg-helios"><div><span>EVIDENCE LAYER</span><b>FORTYGUARD</b><small>provider thermal observations</small></div><i>→</i><div className="active"><span>DECISION LAYER</span><b>HELIOS</b><small>diagnose · act · optimize · verify</small></div></div></section>
  <div className="story-flow">{FLOW.map((x,i)=><div key={x}><b>{x}</b>{i<FLOW.length-1&&<i>→</i>}</div>)}</div>
  <section className="live-decision"><div className="decision-heading"><div><div className="eyebrow">LIVE PHOENIX DECISION</div><h2>One evidence footprint. One actionable portfolio.</h2></div><span>LIVE PROVIDER FOOTPRINT · PHX-DOWNTOWN ONLY</span></div>{unavailable?<div className="decision-unavailable">Decision data unavailable. {unavailable} <button onClick={()=>{provider.retry();optimizer.retry()}}>Retry</button></div>:<><div className="decision-chain"><div><b>{provider.loading?"—":cells.length}</b><span>VERIFIED CELLS</span></div><i>→</i><div><b>{cells.length?fmt(va,1):"—"}</b><span>VA-TEU BURDEN</span></div><i>→</i><div><b>{money(n(opt,"total_cost"))}</b><span>PORTFOLIO</span></div><i>→</i><div><b>{s(opt,"selected_count")}</b><span>ACTIONS</span></div><i>→</i><div className="accent"><b>{fmt(n(opt,"teu_reduction"),1)}</b><span>MODELED TEU REDUCTION</span></div></div><div className="decision-meta"><span>{fmt(n(opt,"va_teu_reduction"),1)} modeled VA-TEU reduction</span><span>{s(opt,"solver_status")} · CP-SAT optimized</span><span>Confidence {fmt(n(opt,"confidence"),2)}</span><strong>Human review required</strong></div></>}</section>
  <div className="command-grid"><section className="panel"><div className="section-kicker">DIAGNOSE</div><h2>Burden is not distributed equally.</h2>{provider.loading?<div className="chart-skeleton">Loading live burden…</div>:cells.length?<div className="chart-wrap"><ResponsiveContainer width="100%" height={300}><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="cell"/><YAxis/><Tooltip/><Bar dataKey="TEU" fill="var(--cyan)" radius={[4,4,0,0]}/><Bar dataKey="VA-TEU" fill="var(--acid)" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>:<div className="empty compact-empty">No provider burden data available.</div>}</section><section className="panel posture"><div className="section-kicker">TRUTH BOUNDARY</div><h2>See the city. Trust only what is observed.</h2><p>HELIOS is Phoenix-scale in architecture. Today’s provider-validated operational footprint is four downtown cells. Unobserved Phoenix remains neutral—never assigned fabricated heat values.</p><div className="posture-links"><Link href="/investment"><b>Optimize investment</b><span>Turn evidence into a budget-feasible portfolio →</span></Link><Link href="/thermalway"><b>Protect movement</b><span>Compare fastest and thermal-safe routes →</span></Link><Link href="/evidence"><b>Verify every claim</b><span>Inspect provenance and uncertainty →</span></Link></div><div className="runtime-note">Gemma 4: {system.loading?"checking":runtime?.intelligence?.reachable?"ready behind firewall":"unavailable / fallback disclosed"}</div></section></div>
 </div>
}
