"use client";
import Link from "next/link";
import {Bar,BarChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {E,arr,n,providerOptimizer,money,fmt,s} from "@/lib/domain";
import {useLive} from "./useLive";
import {startJudgeTour} from "./JudgeTour";
import {useDecision} from "./DecisionContext";
import DecisionTrace from "./DecisionTrace";

const FLOW=["OBSERVE","DIAGNOSE","INTERVENE","SIMULATE","OPTIMIZE","PROTECT","EXPLAIN","VERIFY"];
export default function Command(){
 const provider=useLive(E.provider),optimizer=useLive(E.optimizer),system=useLive(E.system),interventions=useLive(E.interventions);
 const {activeCellId,activeCell,setActiveCellId}=useDecision();
 const cells=arr(provider.data),opt=providerOptimizer(optimizer.data),runtime:any=system.data??{},candidates=arr(interventions.data);
 const teu=cells.reduce((z,x)=>z+(n(x,"teu")??0),0),va=cells.reduce((z,x)=>z+(n(x,"va_teu")??0),0);
 const chart=cells.map(x=>({cell:s(x,"cell_id").replace("phx-cell-","Cell "),TEU:n(x,"teu")??0,"VA-TEU":n(x,"va_teu")??0,id:s(x,"cell_id")})).sort((a,b)=>b["VA-TEU"]-a["VA-TEU"]);
 const unavailable=provider.error||optimizer.error;
 const activeCandidates=candidates.filter(x=>String(x.cell_id)===activeCellId),activeSelected=activeCandidates.filter(x=>x.selected);
 const maxVa=cells.length?Math.max(...cells.map(x=>n(x,"va_teu")??-Infinity)):null;
 const maxTeu=cells.length?Math.max(...cells.map(x=>n(x,"teu")??-Infinity)):null;
 const activeLabels=[activeCell&&n(activeCell,"va_teu")===maxVa?"Highest observed VA-TEU":null,activeCell&&n(activeCell,"teu")===maxTeu?"Highest observed TEU":null,activeSelected.length?"Selected for portfolio":"No selected action"].filter(Boolean);
 return <div className="page command-page">
  <section className="judge-hero"><div className="hero-copy"><div className="eyebrow">PHOENIX URBAN HEAT INTERVENTION OPERATING SYSTEM</div><h1>Cities already know where it’s hot.<br/><em>HELIOS decides what to do next.</em></h1><p>FortyGuard observes urban heat. HELIOS converts those observations into exposure intelligence, cooling interventions, modeled counterfactuals, safer mobility, optimized investment and governed AI.</p><div className="brand-line">Don’t map the heat. <b>Rewrite it.</b></div><div className="cta"><button onClick={startJudgeTour}>Start Judge Tour</button><Link className="secondary" href="/atlas">Enter live decision loop</Link></div></div><div className="fg-helios"><div><span>EVIDENCE LAYER</span><b>FORTYGUARD</b><small>provider thermal observations</small></div><i>→</i><div className="active"><span>DECISION LAYER</span><b>HELIOS</b><small>diagnose · simulate · optimize · verify</small></div></div></section>
  <div className="story-flow expanded">{FLOW.map((x,i)=><div key={x}><b>{x}</b>{i<FLOW.length-1&&<i>→</i>}</div>)}</div>
  <section className="live-decision"><div className="decision-heading"><div><div className="eyebrow">LIVE PHOENIX DECISION</div><h2>One evidence footprint. One closed-loop decision system.</h2></div><span>4 CELLS OBSERVED · THE REST INTENTIONALLY UNKNOWN</span></div>{unavailable?<div className="decision-unavailable">Decision data unavailable. {unavailable} <button onClick={()=>{provider.retry();optimizer.retry()}}>Retry</button></div>:<><div className="decision-chain"><div><b>{provider.loading?"—":cells.length}</b><span>VERIFIED CELLS</span></div><i>→</i><div><b>{cells.length?fmt(va,1):"—"}</b><span>VA-TEU BURDEN</span></div><i>→</i><div><b>{money(n(opt,"total_cost"))}</b><span>PORTFOLIO</span></div><i>→</i><div><b>{s(opt,"selected_count")}</b><span>ACTIONS</span></div><i>→</i><div className="accent"><b>{fmt(n(opt,"teu_reduction"),1)}</b><span>MODELED TEU REDUCTION</span></div></div><div className="decision-meta"><span>{fmt(n(opt,"va_teu_reduction"),1)} modeled VA-TEU reduction</span><span>{s(opt,"solver_status")} · CP-SAT optimized</span><span>Confidence {fmt(n(opt,"confidence"),2)}</span><strong>Human review required</strong></div></>}</section>
  <section className="active-decision-card"><div><div className="section-kicker">ACTIVE DECISION ENTITY</div><h2>{activeCellId??"Selecting highest observed VA-TEU cell…"}</h2><div className="entity-tags">{activeLabels.map(x=><span key={String(x)}>{x}</span>)}</div></div><div className="entity-metrics"><div><span>TEU</span><b>{fmt(n(activeCell,"teu"),1)}</b></div><div><span>VA-TEU</span><b>{fmt(n(activeCell,"va_teu"),1)}</b></div><div><span>Temperature</span><b>{fmt(n(activeCell,"current_c"),1)} °C</b></div><div><span>Confidence</span><b>{fmt(n(activeCell,"confidence"),2)}</b></div></div><div className="entity-actions"><Link href="/interventions">Intervene + simulate</Link><Link href="/investment">See portfolio</Link><Link href="/evidence">Verify lineage</Link></div></section>
  <div className="command-grid"><section className="panel"><div className="section-kicker">DIAGNOSE · EQUITY</div><h2>Not every degree of heat creates the same human burden.</h2><p className="muted">TEU captures thermal exposure burden. VA-TEU applies vulnerability context so planning decisions do not optimize exposure while ignoring who bears it.</p>{provider.loading?<div className="chart-skeleton">Loading live burden…</div>:cells.length?<div className="chart-wrap"><ResponsiveContainer width="100%" height={300}><BarChart data={chart} onClick={(state:any)=>{const id=state?.activePayload?.[0]?.payload?.id;if(id)setActiveCellId(id)}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="cell"/><YAxis/><Tooltip/><Bar dataKey="TEU" fill="var(--cyan)" radius={[4,4,0,0]}/><Bar dataKey="VA-TEU" fill="var(--acid)" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>:<div className="empty compact-empty">No provider burden data available.</div>}<small className="chart-hint">Click a bar group to carry that cell through the HELIOS decision loop.</small></section><section className="panel posture"><div className="section-kicker">TRUTH BOUNDARY</div><h2>See the city. Trust only what is observed.</h2><p>HELIOS is Phoenix-scale in architecture. Today’s provider-validated operational footprint is four downtown cells. Unobserved Phoenix remains neutral—never assigned fabricated heat intelligence.</p><div className="posture-links"><Link href="/atlas"><b>Observe the footprint</b><span>Inspect only verified cells →</span></Link><Link href="/interventions"><b>Change the active cell</b><span>Before → intervention → modeled after →</span></Link><Link href="/thermalway"><b>Protect movement</b><span>Fastest vs thermal-safe route →</span></Link></div><div className="runtime-note">Gemma 4: {system.loading?"checking":runtime?.intelligence?.reachable?"ready behind firewall":"unavailable / fallback disclosed"}</div></section></div>
  <DecisionTrace/>
 </div>
}
