"use client";
import {useRef} from "react";
import {Bar,BarChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {E,arr,n,providerOptimizer,money,fmt,labelAction,s} from "@/lib/domain";
import {useLive} from "./useLive";

export default function Investment(){
 const ox=useLive(E.optimizer),ix=useLive(E.interventions),target=useRef<HTMLElement|null>(null);
 const opt=providerOptimizer(ox.data),candidates=arr(ix.data),ranked=[...candidates].sort((a,b)=>(n(b,"teu_reduction")??0)-(n(a,"teu_reduction")??0));
 const selected=ranked.filter(x=>x.selected),chart=(selected.length?selected:ranked.slice(0,6)).map(x=>({name:`${labelAction(x).replaceAll("_"," ")} · ${s(x,"cell_id").replace("phx-cell-","")}`,TEU:n(x,"teu_reduction")??0,"VA-TEU":n(x,"va_teu_reduction")??0}));
 const error=ox.error||ix.error;
 return <div className="page investment-page"><div className="page-title money-title"><div><div className="eyebrow">OPTIMIZE · PROVIDER-NATIVE DECISION</div><h1>If Phoenix gives HELIOS $100,000, what should it do?</h1><p>HELIOS converts heat evidence into a ranked, budget-constrained cooling portfolio.</p></div><button onClick={()=>target.current?.scrollIntoView({behavior:"smooth"})}>See why these actions won ↓</button></div>
  {error&&<div className="decision-unavailable">Portfolio data unavailable: {error} <button onClick={()=>{ox.retry();ix.retry()}}>Retry</button></div>}
  <section className="portfolio-hero"><div className="portfolio-metrics"><article><span>Budget available</span><b>{ox.loading?"—":money(n(opt,"budget"))}</b></article><article className="accent"><span>Selected investment</span><b>{money(n(opt,"total_cost"))}</b></article><article><span>Actions selected</span><b>{s(opt,"selected_count")}</b></article><article><span>Modeled TEU reduction</span><b>{fmt(n(opt,"teu_reduction"),1)}</b></article><article><span>Modeled VA-TEU reduction</span><b>{fmt(n(opt,"va_teu_reduction"),1)}</b></article></div><aside><span>SOLVER STATUS</span><strong>{s(opt,"solver_status","status").toUpperCase()}</strong><b>CP-SAT</b><div>Confidence {fmt(n(opt,"confidence"),2)}</div><div className="review">Human review required</div><small>Modeled portfolio—not guaranteed cooling.</small></aside></section>
  <div className="investment-grid"><section className="panel"><div className="section-kicker">SELECTED PORTFOLIO</div><h2>Modeled benefit by winning action</h2>{chart.length?<div className="chart-wrap"><ResponsiveContainer width="100%" height={340}><BarChart data={chart} layout="vertical" margin={{left:18}}><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number"/><YAxis type="category" dataKey="name" width={122}/><Tooltip/><Bar dataKey="TEU" fill="var(--cyan)" radius={[0,4,4,0]}/><Bar dataKey="VA-TEU" fill="var(--acid)" radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div>:<div className="empty compact-empty">No candidate benefit data available.</div>}</section><section className="panel rationale"><div className="section-kicker">WHY THIS PORTFOLIO</div><h2>Budget feasible. Burden weighted. Reviewable.</h2><p>CP-SAT compares modeled TEU and vulnerability-adjusted benefit under the available budget and intervention constraints. Selected actions remain planning recommendations until human approval.</p><div className="fact-list"><div><span>Budget utilization</span><b>{n(opt,"budget")&&n(opt,"total_cost")?fmt((n(opt,"total_cost")!/n(opt,"budget")!)*100,0)+"%":"—"}</b></div><div><span>Truth category</span><b>{s(opt,"truth_category")}</b></div><div><span>Decision status</span><b>{s(opt,"decision_status")}</b></div></div><details className="technical"><summary>Technical optimizer record</summary><pre>{JSON.stringify(opt,null,2)}</pre></details></section></div>
  <section className="ranked-section" ref={target}><div className="section-head"><div><div className="section-kicker">CANDIDATE COMPARISON</div><h2>Why these actions won</h2></div><span>Selected flags come directly from the provider-native optimizer record.</span></div>{ix.loading?<div className="empty compact-empty">Loading candidate comparison…</div>:<div className="ranked-list">{ranked.map((x,i)=><article key={s(x,"id")} className={x.selected?"selected":""}><span className="rank">{String(i+1).padStart(2,"0")}</span><div className="action-name"><b>{labelAction(x).replaceAll("_"," ")}</b><span>{s(x,"cell_id")}</span></div><div><span>Cost</span><b>{money(n(x,"estimated_cost"))}</b></div><div><span>Modeled TEU</span><b>{fmt(n(x,"teu_reduction"),2)}</b></div><div><span>Modeled VA-TEU</span><b>{fmt(n(x,"va_teu_reduction"),2)}</b></div><div><span>Confidence</span><b>{fmt(n(x,"confidence"),2)}</b></div><strong>{x.selected?"SELECTED":"NOT SELECTED"}</strong></article>)}</div>}</section>
 </div>
}
