"use client";
import {useMemo,useRef} from "react";
import {Bar,BarChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {E,arr,n,providerOptimizer,money,fmt,labelAction,s} from "@/lib/domain";
import {useLive} from "./useLive";
import {useDecision} from "./DecisionContext";
import DecisionTrace from "./DecisionTrace";

export default function Investment(){
 const ox=useLive(E.optimizer),ix=useLive(E.interventions),target=useRef<HTMLElement|null>(null),{activeCellId}=useDecision();
 const opt=providerOptimizer(ox.data),candidates=arr(ix.data),ranked=[...candidates].sort((a,b)=>(n(b,"va_teu_reduction")??0)-(n(a,"va_teu_reduction")??0));
 const selected=ranked.filter(x=>x.selected),chart=(selected.length?selected:ranked.slice(0,6)).map(x=>({name:`${labelAction(x).replaceAll("_"," ")} · ${s(x,"cell_id").replace("phx-cell-","")}`,TEU:n(x,"teu_reduction")??0,"VA-TEU":n(x,"va_teu_reduction")??0}));
 const error=ox.error||ix.error;
 const active=ranked.filter(x=>String(x.cell_id)===activeCellId);
 const budget=n(opt,"budget"),cost=n(opt,"total_cost"),util=budget&&cost?cost/budget*100:null;
 const scored=useMemo(()=>ranked.map(x=>{const c=n(x,"estimated_cost"),t=n(x,"teu_reduction"),v=n(x,"va_teu_reduction");return {...x,teuPerDollar:c&&t!==null?t/c:null,vaPerDollar:c&&v!==null?v/c:null}}),[ix.data]);
 return <div className="page investment-page"><div className="page-title money-title"><div><div className="eyebrow">OPTIMIZE · PROVIDER-NATIVE DECISION</div><h1>If Phoenix gives HELIOS $100,000, what should it do?</h1><p>HELIOS converts heat evidence into a ranked, budget-constrained cooling portfolio while preserving vulnerability, confidence and human review.</p></div><button onClick={()=>target.current?.scrollIntoView({behavior:"smooth"})}>See why these actions won ↓</button></div>
  {error&&<div className="decision-unavailable">Portfolio data unavailable: {error} <button onClick={()=>{ox.retry();ix.retry()}}>Retry</button></div>}
  <section className="portfolio-hero"><div className="portfolio-metrics"><article><span>Budget available</span><b>{ox.loading?"—":money(budget)}</b></article><article className="accent"><span>Selected investment</span><b>{money(cost)}</b></article><article><span>Actions selected</span><b>{s(opt,"selected_count")}</b></article><article><span>Modeled TEU reduction</span><b>{fmt(n(opt,"teu_reduction"),1)}</b></article><article><span>Modeled VA-TEU reduction</span><b>{fmt(n(opt,"va_teu_reduction"),1)}</b></article></div><aside><span>SOLVER STATUS</span><strong>{s(opt,"solver_status","status").toUpperCase()}</strong><b>CP-SAT</b><div>Confidence {fmt(n(opt,"confidence"),2)}</div><div>Budget used {fmt(util,0)}%</div><div className="review">Human review required</div><small>Modeled portfolio—not guaranteed cooling.</small></aside></section>
  <section className="active-portfolio"><div><span>ACTIVE DECISION CELL</span><b>{activeCellId??"—"}</b><small>{active.filter(x=>x.selected).length} selected · {active.length} modeled candidates</small></div><div className="active-rationales">{active.slice(0,6).map(x=><article key={s(x,"id")} className={x.selected?"selected":""}><header><b>{labelAction(x).replaceAll("_"," ")}</b><span>{x.selected?"SELECTED":"NOT SELECTED"}</span></header><p>{x.selected?"Included in the authoritative CP-SAT portfolio under the current budget and constraints.":"Not included in the authoritative CP-SAT portfolio under the current budget and constraints."}</p><small>{money(n(x,"estimated_cost"))} · {fmt(n(x,"va_teu_reduction"),1)} modeled VA-TEU benefit · confidence {fmt(n(x,"confidence"),2)}</small></article>)}</div></section>
  <div className="investment-grid"><section className="panel"><div className="section-kicker">SELECTED PORTFOLIO</div><h2>Modeled benefit by winning action</h2>{chart.length?<div className="chart-wrap"><ResponsiveContainer width="100%" height={340}><BarChart data={chart} layout="vertical" margin={{left:18}}><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number"/><YAxis type="category" dataKey="name" width={122}/><Tooltip/><Bar dataKey="TEU" fill="var(--cyan)" radius={[0,4,4,0]}/><Bar dataKey="VA-TEU" fill="var(--acid)" radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div>:<div className="empty compact-empty">No candidate benefit data available.</div>}</section><section className="panel rationale"><div className="section-kicker">WHY THIS PORTFOLIO</div><h2>Budget feasible. Burden weighted. Reviewable.</h2><p>CP-SAT compares modeled benefits under the available budget and constraints. The UI never invents solver causality: selection status comes directly from the authoritative optimizer record.</p><div className="fact-list"><div><span>Budget utilization</span><b>{fmt(util,0)}%</b></div><div><span>Truth category</span><b>{s(opt,"truth_category")}</b></div><div><span>Decision status</span><b>{s(opt,"decision_status")}</b></div></div><details className="technical"><summary>Technical optimizer record</summary><pre>{JSON.stringify(opt,null,2)}</pre></details></section></div>
  <section className="ranked-section" ref={target}><div className="section-head"><div><div className="section-kicker">CANDIDATE COMPARISON</div><h2>Selected vs not selected</h2></div><span>Benefit-per-dollar values are deterministic ratios of backend-provided modeled benefit and cost.</span></div>{ix.loading?<div className="empty compact-empty">Loading candidate comparison…</div>:<div className="ranked-list">{scored.map((x:any,i:number)=><article key={s(x,"id")} className={`${x.selected?"selected":""} ${String(x.cell_id)===activeCellId?"active-cell":""}`}><span className="rank">{String(i+1).padStart(2,"0")}</span><div className="action-name"><b>{labelAction(x).replaceAll("_"," ")}</b><span>{s(x,"cell_id")}</span></div><div><span>Cost</span><b>{money(n(x,"estimated_cost"))}</b></div><div><span>Modeled TEU</span><b>{fmt(n(x,"teu_reduction"),2)}</b><small>{x.teuPerDollar!==null?`${fmt(x.teuPerDollar*1000,2)} / $1k`:"—"}</small></div><div><span>Modeled VA-TEU</span><b>{fmt(n(x,"va_teu_reduction"),2)}</b><small>{x.vaPerDollar!==null?`${fmt(x.vaPerDollar*1000,2)} / $1k`:"—"}</small></div><div><span>Confidence</span><b>{fmt(n(x,"confidence"),2)}</b></div><strong>{x.selected?"SELECTED":"NOT SELECTED"}</strong></article>)}</div>}</section>
  <DecisionTrace compact/>
 </div>
}
