"use client";
import {useEffect,useState} from "react";
import {E,arr,fmt,n,s} from "@/lib/domain";
import {readRuntimeState,type HeliosRuntimeState} from "@/lib/runtime";
import {useLive} from "./useLive";

export default function System(){
 const sx=useLive(E.system),cx=useLive(E.caps),px=useLive(E.provider),ax=useLive(E.accessibility),jx=useLive(E.journeys),dx=useLive(E.decisionScience),gx=useLive(E.agents);
 const s:any=sx.data??{},c:any=cx.data??{},decision:any=dx.data??{};
 const [source,setSource]=useState<HeliosRuntimeState>({mode:"checking"});
 useEffect(()=>{setSource(readRuntimeState());const h=(e:Event)=>setSource((e as CustomEvent<HeliosRuntimeState>).detail);window.addEventListener("helios:runtime-state",h);return()=>window.removeEventListener("helios:runtime-state",h)},[]);
 const items=[["FastAPI",!!s.service],["PostgreSQL / PostGIS",!!s.database?.ready],["Gemma 4",!!s.intelligence?.reachable],["Truth firewall",s.intelligence?.firewall==="enabled"],["FortyGuard operations",!!c.engines?.provider_operations],["Counterfactual engine",!!c.engines?.counterfactual_interventions],["Portfolio optimizer",!!c.engines?.portfolio_optimizer],["ThermalWay",!!c.engines?.thermalway],["Governed agents",!!c.engines?.governed_agents],["Decision science",!!c.engines?.decision_science]];
 return <div className="page system-page"><div className="page-title"><div><div className="eyebrow">READINESS · OPERATIONS · RECOVERY</div><h1>HELIOS Flight Readiness</h1><p>Live service health, evidence coverage, decision engines and the truthful fallback contract used for hackathon judging continuity.</p></div></div>
 <section className="runtime-architecture"><div className={`runtime-mode ${source.mode}`}><span>PUBLIC DATA MODE</span><b>{source.mode==="live"?"LIVE COMPUTE":source.mode==="snapshot"?"VERIFIED SNAPSHOT":source.mode==="offline"?"BACKEND UNAVAILABLE":"CHECKING"}</b><small>{source.mode==="snapshot"?`captured ${source.snapshotAt?new Date(source.snapshotAt).toLocaleString():"at last validated run"}`:"Source state is disclosed globally in the HELIOS shell."}</small></div><div className="runtime-path"><b>VERCEL UI</b><i>→</i><b>SERVER PROXY</b><i>→</i><b>FASTAPI</b><i>→</i><b>POSTGIS + DETERMINISTIC ENGINES</b><i>→</i><b>GEMMA 4 EXPLANATION</b></div></section>
 <div className="health-grid system-health">{items.map(([nm,ok]:any)=><article key={nm}><span>{nm}</span><b className={ok?"ready":"check"}>{ok?"● READY":"△ CHECK"}</b></article>)}</div>
 <div className="system-grid"><section className="panel"><div className="eyebrow">LIVE SYSTEM STATUS</div><h2>Runtime contract</h2><div className="system-facts"><div><span>API routes</span><b>{s.api?.route_count??"—"}</b></div><div><span>Provider cells</span><b>{arr(px.data).length}</b></div><div><span>Accessibility rows</span><b>{arr(ax.data).length}</b></div><div><span>Critical journeys</span><b>{arr(jx.data).length}</b></div><div><span>Agent runs</span><b>{arr(gx.data).length}</b></div><div><span>Decision robustness</span><b>{fmt(n(decision,"robustness_score"),2)}</b></div></div><details className="technical"><summary>Raw runtime status</summary><pre>{JSON.stringify(s,null,2)}</pre></details></section><section className="panel"><div className="eyebrow">JUDGING CONTINUITY</div><h2>Failure is visible, never disguised.</h2><div className="recovery-contract"><article><span>01</span><b>LIVE BACKEND</b><p>Fresh provider, routing, optimizer and Gemma calls use the active local compute tier through the server-side proxy.</p></article><article><span>02</span><b>VERIFIED SNAPSHOT</b><p>Read-only last-validated non-sensitive evidence may be shown with a timestamp if the compute tier is unavailable.</p></article><article><span>03</span><b>DYNAMIC COMPUTE LOCKED</b><p>New Gemma queries and dynamic ThermalWay calculations are never faked from a snapshot.</p></article><article><span>04</span><b>HUMAN REVIEW</b><p>Provider, derived, modeled, optimized and AI-explained outputs keep their truth categories and review gate.</p></article></div></section></div>
 <section className="panel readiness-truth"><div className="section-kicker">NON-NEGOTIABLE TRUTH CONTRACT</div><h2>Operational transparency is a product feature.</h2><div className="truth-contract-grid"><div><span>Provider footprint</span><b>4 downtown Phoenix cells</b></div><div><span>Unobserved Phoenix</span><b>Intentionally unknown</b></div><div><span>Counterfactuals</span><b>Modeled, not causal guarantees</b></div><div><span>ThermalWay TEC</span><b>Planning exposure, not medical risk</b></div><div><span>Gemma</span><b>Explanation, not numeric authority</b></div><div><span>Final decision</span><b>Human review required</b></div></div></section>
 </div>
}
