"use client";
import * as maplibregl from "maplibre-gl";
import "maplibre-gl/dist/maplibre-gl.css";
import {useEffect,useRef,useState} from "react";
import {E,fmt,n} from "@/lib/domain";
type P=[number,number];
const PROFILE:{[key:string]:string}={standard:"General walking trip",child:"Child traveler · heat-sensitive",older_adult:"Older adult · heat-sensitive",outdoor_worker:"Occupational outdoor exposure",mobility_limited:"Mobility-limited traveler"};
const DEMO:{origin:P;destination:P;profile:string}={origin:[-112.0775,33.4465],destination:[-112.0665,33.4545],profile:"older_adult"};
function RouteCard({title,x,color,dashed=false}:{title:string;x:any;color:string;dashed?:boolean}){return <article className="route-card" style={{borderColor:color}}><div className="route-key"><i style={{background:color,borderStyle:dashed?"dashed":"solid"}}/><b>{title}</b><span>{x?.route?.algorithm?.toUpperCase()}</span></div><div className="route-stats"><div><span>Distance</span><b>{fmt((n(x,"distance_m")??0)/1000,2)} km</b></div><div><span>Duration</span><b>{fmt(n(x,"duration_min"),1)} min</b></div><div><span>Modeled TEC</span><b>{fmt(n(x,"thermal_exposure_cost"),1)}</b></div></div></article>}
export default function ThermalWay(){
 const host=useRef<HTMLDivElement|null>(null),mapRef=useRef<maplibregl.Map|null>(null),originRef=useRef<P|null>(null),destRef=useRef<P|null>(null),markers=useRef<maplibregl.Marker[]>([]);
 const[o,setO]=useState<P|null>(null),[d,setD]=useState<P|null>(null),[profile,setProfile]=useState("standard"),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[msg,setMsg]=useState("Click the map to set origin, then destination.");
 function removeRoutes(){const map=mapRef.current;if(map?.getLayer("route-safe"))map.removeLayer("route-safe");if(map?.getLayer("route-fast"))map.removeLayer("route-fast");if(map?.getSource("routes"))map.removeSource("routes")}
 function clearMarkers(){markers.current.forEach(x=>x.remove());markers.current=[]}
 function reset(){removeRoutes();clearMarkers();originRef.current=null;destRef.current=null;setO(null);setD(null);setResult(null);setError(null);setMsg("Click the map to set origin, then destination.")}
 function marker(p:P,label:string,color:string){const el=document.createElement("div");el.className="tw-marker";el.style.background=color;el.textContent=label;markers.current.push(new maplibregl.Marker({element:el}).setLngLat(p).addTo(mapRef.current!))}
 useEffect(()=>{if(!host.current)return;const map=new maplibregl.Map({container:host.current,center:[-112.072,33.4505],zoom:14.3,style:{version:8,sources:{osm:{type:"raster",tiles:["https://tile.openstreetmap.org/{z}/{x}/{y}.png"],tileSize:256,attribution:"© OpenStreetMap contributors"}},layers:[{id:"osm",type:"raster",source:"osm"}]} as any,attributionControl:false});mapRef.current=map;map.addControl(new maplibregl.NavigationControl(),"top-right");map.addControl(new maplibregl.AttributionControl({compact:true}),"bottom-right");map.on("click",e=>{const p:P=[e.lngLat.lng,e.lngLat.lat];if(!originRef.current){originRef.current=p;setO(p);setMsg("Origin set. Click destination.");marker(p,"A","#ff8b4c")}else if(!destRef.current){destRef.current=p;setD(p);setMsg("Destination set. Compare routes.");marker(p,"B","#d9ff53")}else{reset();originRef.current=p;setO(p);setMsg("New origin set. Click destination.");marker(p,"A","#ff8b4c")}});return()=>map.remove()},[]);
 async function comparePoints(origin:P,destination:P,traveler:string){setBusy(true);setError(null);setMsg("Computing A* fastest and Dijkstra thermal-safe routes…");try{const x:any=await E.compare(origin,destination,traveler);setResult(x);const map=mapRef.current!;removeRoutes();const fc:any={type:"FeatureCollection",features:[{type:"Feature",properties:{mode:"fastest"},geometry:x.fastest.route},{type:"Feature",properties:{mode:"safe"},geometry:x.thermal_safe.route}]};map.addSource("routes",{type:"geojson",data:fc});map.addLayer({id:"route-fast",type:"line",source:"routes",filter:["==","mode","fastest"],paint:{"line-color":"#ff8b4c","line-width":5}});map.addLayer({id:"route-safe",type:"line",source:"routes",filter:["==","mode","safe"],paint:{"line-color":"#d9ff53","line-width":6,"line-dasharray":[1.2,1.2]}});const bounds=new maplibregl.LngLatBounds();x.fastest.route.coordinates.forEach((p:P)=>bounds.extend(p));x.thermal_safe.route.coordinates.forEach((p:P)=>bounds.extend(p));map.fitBounds(bounds,{padding:70});setMsg("Real OSM routes rendered. Thermal cost remains a modeled planning metric.")}catch(e:any){setError(e.message);setMsg("Route comparison unavailable.")}finally{setBusy(false)}}
 async function compare(){if(!o||!d)return;await comparePoints(o,d,profile)}
 async function runDemo(){reset();clearMarkers();originRef.current=DEMO.origin;destRef.current=DEMO.destination;setO(DEMO.origin);setD(DEMO.destination);setProfile(DEMO.profile);marker(DEMO.origin,"A","#ff8b4c");marker(DEMO.destination,"B","#d9ff53");await comparePoints(DEMO.origin,DEMO.destination,DEMO.profile)}
 const fastTec=n(result?.fastest,"thermal_exposure_cost"),saved=n(result?.exposure_budget,"thermal_cost_saved"),pct=fastTec&&saved!==null?saved/fastTec*100:null;
 return <div className="page thermalway-page"><div className="page-title"><div><div className="eyebrow">PROTECT · CLIMATE-SAFE MOBILITY</div><h1>The shortest route is not always the safest route in extreme heat.</h1><p>Compare fastest arrival against a thermal-exposure-aware alternative on the real Phoenix OSM network.</p></div><button className="page-cta" onClick={runDemo} disabled={busy}>{busy?"Running live route…":"▶ Run Phoenix Heat-Safe Demo"}</button></div>
 <div className="human-impact">For heat-sensitive trips, HELIOS can trade a small amount of travel efficiency for lower modeled thermal exposure. The one-click scenario uses a prevalidated Phoenix origin/destination pair and calls the live routing API.</div>
 <div className="tw-layout"><section className="map-card"><div className="route-controls"><label>Traveler profile<select value={profile} onChange={e=>setProfile(e.target.value)}>{Object.keys(PROFILE).map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select></label><span>{PROFILE[profile]}</span><button onClick={compare} disabled={!o||!d||busy}>{busy?"Comparing…":"Compare routes"}</button><button className="ghost" onClick={reset}>Reset</button></div><div ref={host} className="tw-map"/><div className="map-note">{error?<span className="errorbox">{error} · Retry with Compare routes.</span>:msg}</div></section><aside className="route-side"><section className="panel journey-panel"><div className="section-kicker">JOURNEY</div><div className="route-points"><div><span>A · Origin</span><b>{o?o.map(x=>x.toFixed(5)).join(", "):"Click map"}</b></div><div><span>B · Destination</span><b>{d?d.map(x=>x.toFixed(5)).join(", "):"Click map"}</b></div></div></section>{result&&<><div className="route-versus"><RouteCard title="FASTEST ROUTE" x={result.fastest} color="#ff8b4c"/><i>VS</i><RouteCard title="THERMAL-SAFE ROUTE" x={result.thermal_safe} color="#d9ff53" dashed/></div><section className="exposure-result"><div><span>Modeled TEC avoided</span><b>{fmt(saved,1)}</b></div><div><span>Extra travel time</span><b>{fmt(n(result.exposure_budget,"extra_minutes"),1)} min</b></div><div><span>Modeled TEC reduction</span><b>{pct!==null?`${fmt(pct,1)}%`:"—"}</b></div></section>{pct!==null&&<div className="route-verdict">+{fmt(n(result.exposure_budget,"extra_minutes"),1)} min travel time for <b>{fmt(pct,1)}% lower modeled thermal exposure cost.</b></div>}</>}<section className="truth-callout"><b>Planning exposure metric—not medical risk.</b><p>Fastest uses A*. Thermal-safe uses Dijkstra weighted by modeled thermal exposure.</p><small>{result?.fastest?.truth_category??"real_osm_provider_thermal_modelled_cost"}</small></section></aside></div>{result&&<details className="technical"><summary>Technical route response</summary><pre>{JSON.stringify(result,null,2)}</pre></details>}</div>
}
