"use client";
import * as maplibregl from "maplibre-gl";
import "maplibre-gl/dist/maplibre-gl.css";
import {useEffect,useRef,useState} from "react";
import {E,fmt,n} from "@/lib/domain";
type P=[number,number];
function Card({title,x,color,dashed=false}:{title:string;x:any;color:string;dashed?:boolean}){return <article className="route-card" style={{borderColor:color}}><div className="route-key"><i style={{background:color,borderStyle:dashed?"dashed":"solid"}}/><b>{title}</b><span>{x?.route?.algorithm?.toUpperCase()}</span></div><div className="route-stats"><div><span>Distance</span><b>{fmt((n(x,"distance_m")??0)/1000,2)} km</b></div><div><span>Duration</span><b>{fmt(n(x,"duration_min"),1)} min</b></div><div><span>TEC</span><b>{fmt(n(x,"thermal_exposure_cost"),1)}</b></div></div></article>}
export default function ThermalWay(){
 const host=useRef<HTMLDivElement|null>(null),mapRef=useRef<maplibregl.Map|null>(null),originRef=useRef<P|null>(null),destRef=useRef<P|null>(null),markers=useRef<maplibregl.Marker[]>([]);
 const[o,setO]=useState<P|null>(null),[d,setD]=useState<P|null>(null),[profile,setProfile]=useState("standard"),[r,setR]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[msg,setMsg]=useState("Click the map to set origin, then destination.");
 function clearMap(){markers.current.forEach(x=>x.remove());markers.current=[];const map=mapRef.current;if(map?.getLayer("route-safe"))map.removeLayer("route-safe");if(map?.getLayer("route-fast"))map.removeLayer("route-fast");if(map?.getSource("routes"))map.removeSource("routes")}
 function reset(){clearMap();originRef.current=null;destRef.current=null;setO(null);setD(null);setR(null);setError(null);setMsg("Click the map to set origin, then destination.")}
 function marker(p:P,label:string,color:string){const el=document.createElement("div");el.className="tw-marker";el.style.background=color;el.textContent=label;markers.current.push(new maplibregl.Marker({element:el}).setLngLat(p).addTo(mapRef.current!))}
 useEffect(()=>{if(!host.current)return;const map=new maplibregl.Map({container:host.current,center:[-112.072,33.4505],zoom:14.3,style:{version:8,sources:{osm:{type:"raster",tiles:["https://tile.openstreetmap.org/{z}/{x}/{y}.png"],tileSize:256,attribution:"© OpenStreetMap contributors"}},layers:[{id:"osm",type:"raster",source:"osm"}]} as any,attributionControl:false});mapRef.current=map;map.addControl(new maplibregl.NavigationControl(),"top-right");map.addControl(new maplibregl.AttributionControl({compact:true}),"bottom-right");map.on("click",e=>{const p:P=[e.lngLat.lng,e.lngLat.lat];if(!originRef.current){originRef.current=p;setO(p);setMsg("Origin set. Click destination.");marker(p,"A","#ff8b4c")}else if(!destRef.current){destRef.current=p;setD(p);setMsg("Destination set. Compare routes.");marker(p,"B","#d9ff53")}else{reset();originRef.current=p;setO(p);setMsg("New origin set. Click destination.");marker(p,"A","#ff8b4c")}});return()=>map.remove()},[]);
 async function compare(){if(!o||!d)return;setBusy(true);setError(null);setMsg("Computing A* fastest and Dijkstra thermal-safe routes…");try{const x:any=await E.compare(o,d,profile);setR(x);const map=mapRef.current!;const fc:any={type:"FeatureCollection",features:[{type:"Feature",properties:{mode:"fastest"},geometry:x.fastest.route},{type:"Feature",properties:{mode:"safe"},geometry:x.thermal_safe.route}]};map.addSource("routes",{type:"geojson",data:fc});map.addLayer({id:"route-fast",type:"line",source:"routes",filter:["==","mode","fastest"],paint:{"line-color":"#ff8b4c","line-width":5}});map.addLayer({id:"route-safe",type:"line",source:"routes",filter:["==","mode","safe"],paint:{"line-color":"#d9ff53","line-width":6,"line-dasharray":[1.2,1.2]}});const b=new maplibregl.LngLatBounds();x.fastest.route.coordinates.forEach((p:P)=>b.extend(p));x.thermal_safe.route.coordinates.forEach((p:P)=>b.extend(p));map.fitBounds(b,{padding:70});setMsg("Two verified OSM-network routes rendered.")}catch(e:any){setError(e.message);setMsg("Route comparison failed.")}finally{setBusy(false)}}
 return <div className="page"><div className="page-title"><div><div className="eyebrow">PLANNING MODE · CLIMATE-SAFE MOBILITY</div><h1>ThermalWay</h1><p>Fastest optimizes travel time. Thermal-safe minimizes modeled thermal exposure cost.</p></div></div><div className="tw-layout"><section className="map-card"><div className="route-controls"><select aria-label="Traveler profile" value={profile} onChange={e=>setProfile(e.target.value)}>{["standard","child","older_adult","outdoor_worker","mobility_limited"].map(x=><option key={x}>{x}</option>)}</select><button onClick={compare} disabled={!o||!d||busy}>{busy?"Comparing…":"Compare routes"}</button><button className="ghost" onClick={reset}>Reset</button></div><div ref={host} className="tw-map"/><div className="map-note">{error?<span className="errorbox">{error} · retry with Compare routes</span>:msg}</div></section><aside className="route-side"><section className="panel"><div className="eyebrow">JOURNEY · {profile.replaceAll("_"," ")}</div><div className="route-points"><div><span>Origin</span><b>{o?o.map(x=>x.toFixed(5)).join(", "):"Not set"}</b></div><div><span>Destination</span><b>{d?d.map(x=>x.toFixed(5)).join(", "):"Not set"}</b></div></div></section>{r&&<><Card title="Fastest" x={r.fastest} color="#ff8b4c"/><Card title="Thermal-safe" x={r.thermal_safe} color="#d9ff53" dashed/><section className="panel"><div className="fact-list compact"><div><span>TEC saved</span><b>{fmt(n(r.exposure_budget,"thermal_cost_saved"),1)}</b></div><div><span>Extra minutes</span><b>{fmt(n(r.exposure_budget,"extra_minutes"),1)}</b></div></div></section></>}<section className="panel"><div className="eyebrow">TRUTH CATEGORY</div><h2>real_osm_provider_thermal_modelled_cost</h2><p className="muted">TEC is a modeled planning metric, not medical risk.</p></section></aside></div>{r&&<details className="technical"><summary>Technical route response</summary><pre>{JSON.stringify(r,null,2)}</pre></details>}</div>}
