"""Thermal intelligence core."""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
revision='0002_thermal_core'; down_revision='0001_foundation'; branch_labels=None; depends_on=None
def upgrade():
    op.create_table('areas', sa.Column('id',sa.String(64),primary_key=True), sa.Column('city_id',sa.String(64),sa.ForeignKey('cities.id',ondelete='CASCADE'),nullable=False), sa.Column('name',sa.String(160),nullable=False), sa.Column('area_type',sa.String(64),nullable=False,server_default='aoi'), sa.Column('geometry',Geometry('MULTIPOLYGON',srid=4326),nullable=False), sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_index('ix_areas_city_id','areas',['city_id'])
    op.create_table('thermal_cells', sa.Column('id',sa.String(64),primary_key=True), sa.Column('area_id',sa.String(64),sa.ForeignKey('areas.id',ondelete='CASCADE'),nullable=False), sa.Column('grid_key',sa.String(128),nullable=False), sa.Column('resolution_m',sa.Integer(),nullable=False), sa.Column('geometry',Geometry('POLYGON',srid=4326),nullable=False), sa.Column('centroid',Geometry('POINT',srid=4326),nullable=False), sa.Column('created_at',sa.DateTime(timezone=True),nullable=False), sa.UniqueConstraint('area_id','grid_key',name='uq_thermal_cell_grid'))
    op.create_index('ix_thermal_cells_area_id','thermal_cells',['area_id'])
    op.create_table('thermal_observations', sa.Column('id',sa.String(36),primary_key=True), sa.Column('cell_id',sa.String(64),sa.ForeignKey('thermal_cells.id',ondelete='CASCADE'),nullable=False), sa.Column('observed_at',sa.DateTime(timezone=True),nullable=False), sa.Column('temperature_c',sa.Float(),nullable=False), sa.Column('apparent_temperature_c',sa.Float()), sa.Column('humidity_pct',sa.Float()), sa.Column('heat_index_c',sa.Float()), sa.Column('source_type',sa.String(32),nullable=False), sa.Column('source_name',sa.String(128),nullable=False), sa.Column('source_activity_id',sa.String(128)), sa.Column('quality_label',sa.String(32),nullable=False), sa.Column('metadata_json',sa.JSON(),nullable=False), sa.Column('created_at',sa.DateTime(timezone=True),nullable=False), sa.UniqueConstraint('cell_id','observed_at','source_name',name='uq_thermal_observation'))
    op.create_index('ix_thermal_obs_cell_time','thermal_observations',['cell_id','observed_at'])
    op.create_table('thermal_baselines', sa.Column('id',sa.String(36),primary_key=True), sa.Column('cell_id',sa.String(64),sa.ForeignKey('thermal_cells.id',ondelete='CASCADE'),nullable=False), sa.Column('bucket_key',sa.String(64),nullable=False), sa.Column('mean_c',sa.Float(),nullable=False), sa.Column('std_c',sa.Float(),nullable=False), sa.Column('p90_c',sa.Float(),nullable=False), sa.Column('sample_count',sa.Integer(),nullable=False), sa.Column('computed_at',sa.DateTime(timezone=True),nullable=False), sa.UniqueConstraint('cell_id','bucket_key',name='uq_thermal_baseline'))
    op.create_table('thermal_metrics', sa.Column('id',sa.String(36),primary_key=True), sa.Column('cell_id',sa.String(64),sa.ForeignKey('thermal_cells.id',ondelete='CASCADE'),nullable=False), sa.Column('observed_at',sa.DateTime(timezone=True),nullable=False), sa.Column('anomaly_c',sa.Float()), sa.Column('z_score',sa.Float()), sa.Column('exceedance_c',sa.Float()), sa.Column('persistence_hours',sa.Float(),nullable=False,server_default='0'), sa.Column('severity_score',sa.Float(),nullable=False), sa.Column('confidence',sa.Float(),nullable=False), sa.Column('components_json',sa.JSON(),nullable=False), sa.Column('created_at',sa.DateTime(timezone=True),nullable=False), sa.UniqueConstraint('cell_id','observed_at',name='uq_thermal_metric'))
    op.create_index('ix_thermal_metrics_time','thermal_metrics',['observed_at'])
    op.create_table('thermal_hotspots', sa.Column('id',sa.String(36),primary_key=True), sa.Column('area_id',sa.String(64),sa.ForeignKey('areas.id',ondelete='CASCADE'),nullable=False), sa.Column('detected_at',sa.DateTime(timezone=True),nullable=False), sa.Column('status',sa.String(32),nullable=False), sa.Column('severity',sa.String(32),nullable=False), sa.Column('peak_temperature_c',sa.Float(),nullable=False), sa.Column('mean_anomaly_c',sa.Float(),nullable=False), sa.Column('max_persistence_hours',sa.Float(),nullable=False), sa.Column('cell_count',sa.Integer(),nullable=False), sa.Column('geometry',Geometry('MULTIPOLYGON',srid=4326),nullable=False), sa.Column('confidence',sa.Float(),nullable=False), sa.Column('metadata_json',sa.JSON(),nullable=False), sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_index('ix_hotspots_area_time','thermal_hotspots',['area_id','detected_at'])
    op.create_table('thermal_events', sa.Column('id',sa.String(36),primary_key=True), sa.Column('area_id',sa.String(64),sa.ForeignKey('areas.id',ondelete='CASCADE'),nullable=False), sa.Column('event_type',sa.String(64),nullable=False), sa.Column('status',sa.String(32),nullable=False), sa.Column('started_at',sa.DateTime(timezone=True),nullable=False), sa.Column('ended_at',sa.DateTime(timezone=True)), sa.Column('peak_severity_score',sa.Float(),nullable=False), sa.Column('peak_temperature_c',sa.Float(),nullable=False), sa.Column('max_persistence_hours',sa.Float(),nullable=False), sa.Column('hotspot_count',sa.Integer(),nullable=False), sa.Column('confidence',sa.Float(),nullable=False), sa.Column('summary_json',sa.JSON(),nullable=False), sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_index('ix_events_area_status','thermal_events',['area_id','status'])
def downgrade():
    op.drop_index('ix_events_area_status',table_name='thermal_events'); op.drop_table('thermal_events')
    op.drop_index('ix_hotspots_area_time',table_name='thermal_hotspots'); op.drop_table('thermal_hotspots')
    op.drop_index('ix_thermal_metrics_time',table_name='thermal_metrics'); op.drop_table('thermal_metrics'); op.drop_table('thermal_baselines')
    op.drop_index('ix_thermal_obs_cell_time',table_name='thermal_observations'); op.drop_table('thermal_observations')
    op.drop_index('ix_thermal_cells_area_id',table_name='thermal_cells'); op.drop_table('thermal_cells')
    op.drop_index('ix_areas_city_id',table_name='areas'); op.drop_table('areas')
